
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\rosit\Escritorio\TEORIA DE SISTEMAS\build\version2-botones\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x729")
window.configure(bg = "#4B0082")


canvas = Canvas(
    window,
    bg = "#4B0082",
    height = 729,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    248.0,
    0.0,
    1000.0,
    729.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    301.0,
    198.0,
    574.0,
    500.0,
    fill="#00827A",
    outline="")

canvas.create_rectangle(
    301.0,
    149.0,
    575.0,
    198.0,
    fill="#210082",
    outline="")

canvas.create_text(
    311.0,
    164.0,
    anchor="nw",
    text="TallaID",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    409.0,
    164.0,
    anchor="nw",
    text="NombreTalla",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_rectangle(
    638.0,
    198.0,
    911.0,
    500.0,
    fill="#00827A",
    outline="")

canvas.create_rectangle(
    638.0,
    149.0,
    912.0,
    198.0,
    fill="#210082",
    outline="")

canvas.create_text(
    648.0,
    164.0,
    anchor="nw",
    text="ColorID",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    746.0,
    164.0,
    anchor="nw",
    text="Color",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_rectangle(
    380.0,
    542.0,
    493.0,
    592.0,
    fill="#008282",
    outline="")

canvas.create_text(
    402.0,
    558.0,
    anchor="nw",
    text="Modificar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_rectangle(
    536.0,
    543.0,
    654.0,
    593.0,
    fill="#008282",
    outline="")

canvas.create_rectangle(
    704.0,
    543.0,
    822.0,
    593.0,
    fill="#008282",
    outline="")

canvas.create_text(
    567.0,
    559.0,
    anchor="nw",
    text="Eliminar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_text(
    733.0,
    559.0,
    anchor="nw",
    text="Agregar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_rectangle(
    1.0,
    0.0,
    249.0,
    729.0,
    fill="#008282",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    126.0,
    116.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=27.0,
    y=542.0,
    width=198.0,
    height=45.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=27.0,
    y=233.0,
    width=198.0,
    height=51.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=27.0,
    y=308.0,
    width=198.0,
    height=44.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=27.0,
    y=382.0,
    width=198.0,
    height=45.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=27.0,
    y=458.0,
    width=198.0,
    height=45.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=27.0,
    y=618.0,
    width=198.0,
    height=45.0
)
window.resizable(False, False)
window.mainloop()
