
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\rosit\Escritorio\TEORIA DE SISTEMAS\build\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x729")
window.configure(bg = "#4B0082")


canvas = Canvas(
    window,
    bg = "#4B0082",
    height = 729,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    248.0,
    0.0,
    1000.0,
    729.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    248.0,
    729.0,
    fill="#008282",
    outline="")

canvas.create_text(
    48.0,
    724.0,
    anchor="nw",
    text="Cerrar sesión",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 25 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    125.0,
    116.0,
    image=image_image_1
)

canvas.create_rectangle(
    27.0,
    311.0,
    225.0,
    355.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    27.0,
    236.0,
    225.0,
    287.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    27.0,
    385.0,
    225.0,
    430.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    27.0,
    461.0,
    225.0,
    506.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    27.0,
    545.0,
    225.0,
    590.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    27.0,
    621.0,
    225.0,
    666.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    69.0,
    250.0,
    anchor="nw",
    text="Dashboard",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    79.0,
    321.0,
    anchor="nw",
    text="Inventario",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    88.0,
    397.0,
    anchor="nw",
    text="Ventas",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    58.0,
    472.0,
    anchor="nw",
    text="Devoluciones",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    73.0,
    555.0,
    anchor="nw",
    text="Productos",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    79.0,
    632.0,
    anchor="nw",
    text="Clientes",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
