
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\rosit\Escritorio\TEORIA DE SISTEMAS\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x729")
window.configure(bg = "#4B0082")


canvas = Canvas(
    window,
    bg = "#4B0082",
    height = 729,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    248.0,
    0.0,
    1000.0,
    729.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    248.0,
    729.0,
    fill="#008282",
    outline="")

canvas.create_text(
    48.0,
    724.0,
    anchor="nw",
    text="Cerrar sesión",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 25 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    125.0,
    116.0,
    image=image_image_1
)

canvas.create_rectangle(
    272.0,
    193.0,
    947.0,
    495.0,
    fill="#00827A",
    outline="")

canvas.create_rectangle(
    272.0,
    144.0,
    947.0,
    193.0,
    fill="#210082",
    outline="")

canvas.create_text(
    282.0,
    159.0,
    anchor="nw",
    text="InventarioID",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    380.0,
    159.0,
    anchor="nw",
    text="VarianteID",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    468.0,
    159.0,
    anchor="nw",
    text="Cantidad",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    545.0,
    159.0,
    anchor="nw",
    text="UbicacionAlmacen",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_text(
    688.0,
    159.0,
    anchor="nw",
    text="UltimaActualizacion",
    fill="#FFFFFF",
    font=("Inter ExtraLightItalic", 15 * -1)
)

canvas.create_rectangle(
    389.0,
    552.0,
    502.0,
    602.0,
    fill="#008282",
    outline="")

canvas.create_rectangle(
    272.0,
    58.0,
    498.0,
    108.0,
    fill="#008282",
    outline="")

canvas.create_text(
    411.0,
    568.0,
    anchor="nw",
    text="Modificar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_text(
    284.0,
    68.0,
    anchor="nw",
    text="Mostrar variantes de producto",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_rectangle(
    545.0,
    553.0,
    663.0,
    603.0,
    fill="#008282",
    outline="")

canvas.create_rectangle(
    713.0,
    553.0,
    831.0,
    603.0,
    fill="#008282",
    outline="")

canvas.create_text(
    576.0,
    569.0,
    anchor="nw",
    text="Eliminar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_text(
    742.0,
    569.0,
    anchor="nw",
    text="Agregar",
    fill="#FFFFFF",
    font=("Inter Bold", 15 * -1)
)

canvas.create_rectangle(
    26.0,
    234.0,
    224.0,
    285.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    26.0,
    309.0,
    224.0,
    353.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    26.0,
    383.0,
    224.0,
    428.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    26.0,
    459.0,
    224.0,
    504.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    26.0,
    543.0,
    224.0,
    588.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    26.0,
    619.0,
    224.0,
    664.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    68.0,
    248.0,
    anchor="nw",
    text="Dashboard",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    78.0,
    319.0,
    anchor="nw",
    text="Inventario",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    87.0,
    395.0,
    anchor="nw",
    text="Ventas",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    57.0,
    470.0,
    anchor="nw",
    text="Devoluciones",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    72.0,
    553.0,
    anchor="nw",
    text="Productos",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)

canvas.create_text(
    78.0,
    630.0,
    anchor="nw",
    text="Clientes",
    fill="#000000",
    font=("Inter ExtraLightItalic", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
